### ISSUE TITLE
Registering controllers to modules instead of global scope

### ISSUE THREAD

**Issue by shlomokraus** [inversify/inversify-express-utils#201]
I've noticed that controllers are automatically registered to global scope when they are imported. A cleaner way would be to allow each package to export its controllers and then load them into the required container, as with any other dependencies. 

Is there a way to do so now or would I need to implement this feature?

**Comment by eropple** [comment]
Also looking at this. Spent a good bit of time scratching my head because I'm pulling in multiple Express apps into a single server and then routing across them by hostname, and the behavior was not what I expected.

**Comment by remojansen** [comment]
Moved to the main repo. https://github.com/inversify/InversifyJS/issues/930

**Comment by robincafolla** [comment]
It seems like there's some debate in the main repo over where this belongs? And it doesn't appear to be resolved. Can you re-open it?
