### ISSUE TITLE
Create a Principal decorator

### ISSUE THREAD

**Issue by tioback** [inversify/inversify-express-utils#205]
I'm trying to create a new decorator to make it simpler to obtain the Principal information, something like:

    @httpGet("/")
    public async getByUser(@principal() principal: Principal): Promise<any> {
        console.log(principal.details);
    }

However, I'm having a hard time understanding the code and can't seem to find out where is it that the parameters values are altered by the `@controller` and/or `@httpMethod` decorators.

Would someone please point me to the right direction so I can do PR?

**EDIT**
As it turns out, I found previous commit #161 that shows some changes in `server.ts`, which I believe might be the right place to do the changes I'm proposing.

**Comment by dcavanagh** [comment]
server.ts line 283

**Comment by tioback** [comment]
May you please check PR #207 , @dcavanagh ?

**Comment by dcavanagh** [comment]
Yes. I have some friends in town for the holiday but I will try to take a
look

Dan

**Comment by remojansen** [comment]
Thanks, @dcavanagh for managing the PR and @tioback for contributing. I will close this issue now. Please remember to report the issues in the main repo next time because it helps us to manage the project in a more efficient way,

**Comment by tioback** [comment]
Hi, @remojansen , you mean the [InversifyJS](https://github.com/inversify/InversifyJS/) repo?
