### ISSUE TITLE
Async/await not working on service

### ISSUE THREAD

**Issue by tomdkt** [inversify/inversify-express-utils#240]
Hello! I'm calling a method with async/await on service layer and it isn't waiting for the final promise. Is this a normal behavior? Because with 'express' it seems like it doesn't.

I'm using:
"node":"10.13.0"
"inversify": "5.0.1"
"inversify-binding-decorators": "3.2.0"
"inversify-express-utils": "6.2.0"
"typescript": "3.0.3"

To test this behavior using the https://github.com/inversify/inversify-express-example: 

1. Modify the folder 'Basic' and add this snippet to UserService. 
2. run with 'ts-node Basic/bootstrap.ts'
3. calling curl localhost:3000/user

Behavior: the 'get' ends and the console continue printing. How do I call an async/await method and then return the response to the client??

```
@injectable()
export class UserService {
  private async run(){
        await this.sleep(2000);
        console.log('Free');
        await this.sleep(2000);
        console.log('Free');
        await this.sleep(2000);
        console.log('Free');
    }
    private sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

  public getUsers(): IUser[] {
    this.run().then(()=>{
      console.log('finish');
    });

    return this.userStorage;
  }
```

**Comment by dcavanagh** [comment]
if you want the `return this.userStorage` to wait for the 'finish' and then to go you need to await the `this.run()` call and make the getUsers() function async

```typescript
@injectable()
export class UserService {
  private async run(){
        await this.sleep(2000);
        console.log('Free');
        await this.sleep(2000);
        console.log('Free');
        await this.sleep(2000);
        console.log('Free');
    }
    private sleep(ms) {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

  public async getUsers(): Promise<IUser[]> {
    await this.run().then(() => {
      console.log('finish');
    });

    return this.userStorage;
  }
}
```
