### ISSUE TITLE
How do I get access to http server?

### ISSUE THREAD

**Issue by xinghul** [inversify/inversify-express-utils#322]
In order to make it work with graphql subscriptions(or socket in general), I need access to the underlying http server(not Express application).

Is there a way to do that?

**Comment by danieljee** [comment]
Same here. I need access to the underlying http server object for other purposes such as WebSocket.

**Comment by leandrocurioso** [comment]
Any ideas?

**Comment by matewilk** [comment]
+1
Is there any way, in particular I'm looking to use `InversifySocketUtils` so would be happy if there was an option to at least get the underlying https server instance.

**Comment by davx1992** [comment]
Hi All,
maybe it would be useful for you, this is how I got Http instance.
```javascript
        const inversifyExpressServer = new InversifyExpressServer(container);
        inversifyExpressServer.setConfig((app) => {
            // add body parser
            app.use(
                bodyParser.urlencoded({
                    extended: true,
                }),
            );
            app.use(bodyParser.json());
        });

        let app = inversifyExpressServer.build();

        const server = http.createServer(app);
        server.listen(port)
```
As you see after build we get express app instance. This instance could be fed to http.createServer and then server.listen(port).

**Comment by PodaruDragos** [comment]
@davx1992  solution is the preferable one and also the corect one.
app is just an express app not an http server.
