### ISSUE TITLE
Breaking change was introduced - interfaces.ts no longer exports an interface object

### ISSUE THREAD

**Issue by Minibrams** [inversify/inversify-express-utils#352]
The commit d09dfbb7c6f9de90b84e474d4448049cdbc12596 adding ESLint to the project (accidentally?) removed the `export { interfaces } ` from `src/interfaces.ts`. 

It looks like all packages using `inversify-express-utils` that have an `import { interfaces } from 'inversify-express-utils'` will break because of this.

**Comment by anderslangballe** [comment]
I am having this issue as well.

**Comment by dcavanagh** [comment]
@Minibrams @anderslangballe  is this the only breaking change that you can see?

**Comment by dcavanagh** [comment]
added `export * as interfaces from './interfaces';` to src/index.ts
