### ISSUE TITLE
[inversify-express-utils] AuthProvider Unhandled Promise Rejection

### ISSUE THREAD

**Issue by ythomop** [inversify/inversify-express-utils#367]
When an error is thrown/a promise is rejected in the AuthProvider's getUser() method, the server does not ever respond to the client and an Unhandled Promise Rejection Warning is written on the console.

## Expected Behavior
The error handler of the express server should be called and respond appropriately to the client.

## Current Behavior
No server response is sent and the client is left waiting when an error occurs in the AuthProvider.

## Steps to Reproduce
```
  async getUser(req: Request, res: Response, next: NextFunction): Promise<interfaces.Principal> {
    console.log('[AUTH_MD]');
    const token = req.header('X-CONTROL-CENTER-AUTH') as string;
    if (!token) return new Principal(undefined);
    try {
      const user = await this.userService
        .validate(token);
      if (!user) {
        return Promise.reject(new Unauthorized({ path: '' }));
      }
      return new Principal(user);
    } catch (e) {
      return Promise.reject(new InternalServerError({ path: '' }));
    }
  }
}
```

Note: The Unauthorized and InternalServerError classes are from [express-openapi-validator](https://github.com/cdimascio/express-openapi-validator) but the result is the same using even a simple Error.

## Your Environment
* Version used: inversify: ^5.0.1 && inversify-express-utils: ^6.3.2
* Environment name and version (e.g. Chrome 39, node.js 5.4): Docker-node:alpine3.12

**Comment by shyamvala** [comment]
I am curious if this was ever resolved. I was trying to do the same so I can catch an expired token so I can take the user in the front end through a custom flow of refreshing token.

**Comment by hArsh92** [comment]
You can create a method like`handleError` inside the AuthProvider implementation and call it whenever you want to throw error

```typescript
private handleError(error: AppError, res: express.Response, next: express.NextFunction): Promise<interfaces.Principal> {
    res.status(error.statusCode).json(ApiResponse.errorFromException(error));
    next(error);
    return Promise.resolve({
      details: null,
      isAuthenticated: async () => false,
      isInRole: async () => false,
      isResourceOwner: async () => false,
    });
  }
```

```typescript
async getUser(req: Request, res: Response, next: NextFunction): Promise<interfaces.Principal> {
    console.log('[AUTH_MD]');
    const token = req.header('X-CONTROL-CENTER-AUTH') as string;
    if (!token) return this.handleError(new AuthenticationError('Invalid token'), res, next);
    try {
      const user = await this.userService.validate(token);
      if (!user) {
        return this.handleError(new Unauthorized({ path: '' }), res, next);
      }
      return new Principal(user);
    } catch (e) {
      return this,handle(new InternalServerError({ path: '' }), res, next);
    }
  }
}
```
